// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package myproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VMInfo struct {
	Id                   string        `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Status               string        `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	PublicIps            []string      `protobuf:"bytes,4,rep,name=PublicIps,proto3" json:"PublicIps,omitempty"`
	PrivateIps           []string      `protobuf:"bytes,5,rep,name=PrivateIps,proto3" json:"PrivateIps,omitempty"`
	Config               *VMInfoConfig `protobuf:"bytes,6,opt,name=Config,proto3" json:"Config,omitempty"`
	Host                 string        `protobuf:"bytes,7,opt,name=Host,proto3" json:"Host,omitempty"`
	Sn                   string        `protobuf:"bytes,8,opt,name=Sn,proto3" json:"Sn,omitempty"`
	Provider             string        `protobuf:"bytes,9,opt,name=Provider,proto3" json:"Provider,omitempty"`
	CreateUserId         string        `protobuf:"bytes,10,opt,name=CreateUserId,proto3" json:"CreateUserId,omitempty"`
	CreateTime           string        `protobuf:"bytes,11,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	IsTemplate           string        `protobuf:"bytes,12,opt,name=IsTemplate,proto3" json:"IsTemplate,omitempty"`
	VmPathName           string        `protobuf:"bytes,13,opt,name=VmPathName,proto3" json:"VmPathName,omitempty"`
	Desc                 string        `protobuf:"bytes,14,opt,name=Desc,proto3" json:"Desc,omitempty"`
	NetworkInterfaceID   []string      `protobuf:"bytes,15,rep,name=NetworkInterfaceID,proto3" json:"NetworkInterfaceID,omitempty"`
	PortGroupsId         []string      `protobuf:"bytes,16,rep,name=PortGroupsId,proto3" json:"PortGroupsId,omitempty"`
	VolumeId             []string      `protobuf:"bytes,17,rep,name=VolumeId,proto3" json:"VolumeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VMInfo) Reset()         { *m = VMInfo{} }
func (m *VMInfo) String() string { return proto.CompactTextString(m) }
func (*VMInfo) ProtoMessage()    {}
func (*VMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5c47d14aed52854c, []int{0}
}
func (m *VMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMInfo.Unmarshal(m, b)
}
func (m *VMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMInfo.Marshal(b, m, deterministic)
}
func (dst *VMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMInfo.Merge(dst, src)
}
func (m *VMInfo) XXX_Size() int {
	return xxx_messageInfo_VMInfo.Size(m)
}
func (m *VMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VMInfo proto.InternalMessageInfo

func (m *VMInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VMInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VMInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VMInfo) GetPublicIps() []string {
	if m != nil {
		return m.PublicIps
	}
	return nil
}

func (m *VMInfo) GetPrivateIps() []string {
	if m != nil {
		return m.PrivateIps
	}
	return nil
}

func (m *VMInfo) GetConfig() *VMInfoConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *VMInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *VMInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *VMInfo) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *VMInfo) GetCreateUserId() string {
	if m != nil {
		return m.CreateUserId
	}
	return ""
}

func (m *VMInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *VMInfo) GetIsTemplate() string {
	if m != nil {
		return m.IsTemplate
	}
	return ""
}

func (m *VMInfo) GetVmPathName() string {
	if m != nil {
		return m.VmPathName
	}
	return ""
}

func (m *VMInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *VMInfo) GetNetworkInterfaceID() []string {
	if m != nil {
		return m.NetworkInterfaceID
	}
	return nil
}

func (m *VMInfo) GetPortGroupsId() []string {
	if m != nil {
		return m.PortGroupsId
	}
	return nil
}

func (m *VMInfo) GetVolumeId() []string {
	if m != nil {
		return m.VolumeId
	}
	return nil
}

type VMInfoConfig struct {
	Memory               int32    `protobuf:"varint,1,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Cpu                  int32    `protobuf:"varint,2,opt,name=Cpu,proto3" json:"Cpu,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VMInfoConfig) Reset()         { *m = VMInfoConfig{} }
func (m *VMInfoConfig) String() string { return proto.CompactTextString(m) }
func (*VMInfoConfig) ProtoMessage()    {}
func (*VMInfoConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5c47d14aed52854c, []int{1}
}
func (m *VMInfoConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMInfoConfig.Unmarshal(m, b)
}
func (m *VMInfoConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMInfoConfig.Marshal(b, m, deterministic)
}
func (dst *VMInfoConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMInfoConfig.Merge(dst, src)
}
func (m *VMInfoConfig) XXX_Size() int {
	return xxx_messageInfo_VMInfoConfig.Size(m)
}
func (m *VMInfoConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VMInfoConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VMInfoConfig proto.InternalMessageInfo

func (m *VMInfoConfig) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *VMInfoConfig) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func init() {
	proto.RegisterType((*VMInfo)(nil), "myproto.VMInfo")
	proto.RegisterType((*VMInfoConfig)(nil), "myproto.VMInfoConfig")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_5c47d14aed52854c) }

var fileDescriptor_test_5c47d14aed52854c = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xbf, 0x6f, 0xea, 0x30,
	0x10, 0xc7, 0x05, 0x81, 0x40, 0x0e, 0x1e, 0x8f, 0x67, 0xe9, 0x55, 0x56, 0x55, 0x55, 0x88, 0x89,
	0xa5, 0x19, 0xda, 0xa5, 0x3b, 0x48, 0xad, 0x07, 0x50, 0x14, 0x28, 0x7b, 0x20, 0x47, 0x1b, 0x95,
	0xc4, 0x91, 0xed, 0x50, 0xf1, 0xa7, 0x77, 0xab, 0x7c, 0x8e, 0xf8, 0x21, 0x75, 0xbb, 0xfb, 0x7c,
	0x6e, 0xf8, 0xde, 0xd9, 0x00, 0x06, 0xb5, 0x09, 0x4b, 0x25, 0x8d, 0x64, 0x9d, 0xfc, 0x48, 0xc5,
	0xf8, 0xdb, 0x03, 0x7f, 0x3d, 0x17, 0xc5, 0x4e, 0xb2, 0x01, 0x34, 0x45, 0xca, 0x1b, 0xa3, 0xc6,
	0x24, 0x88, 0x9b, 0x22, 0x65, 0x0c, 0x5a, 0x8b, 0x24, 0x47, 0xde, 0x24, 0x42, 0x35, 0xbb, 0x01,
	0x7f, 0x69, 0x12, 0x53, 0x69, 0xee, 0x11, 0xad, 0x3b, 0x76, 0x07, 0x41, 0x54, 0x6d, 0xf6, 0xd9,
	0x56, 0x94, 0x9a, 0xb7, 0x46, 0xde, 0x24, 0x88, 0xcf, 0x80, 0xdd, 0x03, 0x44, 0x2a, 0x3b, 0x24,
	0x06, 0xad, 0x6e, 0x93, 0xbe, 0x20, 0xec, 0x01, 0xfc, 0xa9, 0x2c, 0x76, 0xd9, 0x3b, 0xf7, 0x47,
	0x8d, 0x49, 0xef, 0xf1, 0x7f, 0x58, 0xc7, 0x0b, 0x5d, 0x34, 0x27, 0xe3, 0x7a, 0xc8, 0x06, 0x7b,
	0x95, 0xda, 0xf0, 0x8e, 0x0b, 0x66, 0x6b, 0x1b, 0x7e, 0x59, 0xf0, 0xae, 0x0b, 0xbf, 0x2c, 0xd8,
	0x2d, 0x74, 0x23, 0x25, 0x0f, 0x59, 0x8a, 0x8a, 0x07, 0x44, 0x4f, 0x3d, 0x1b, 0x43, 0x7f, 0xaa,
	0x30, 0x31, 0xf8, 0xa6, 0x51, 0x89, 0x94, 0x03, 0xf9, 0x2b, 0x66, 0x23, 0xbb, 0x7e, 0x95, 0xe5,
	0xc8, 0x7b, 0x34, 0x71, 0x41, 0xac, 0x17, 0x7a, 0x85, 0x79, 0xb9, 0x4f, 0x0c, 0xf2, 0xbe, 0xf3,
	0x67, 0x62, 0xfd, 0x3a, 0x8f, 0x12, 0xf3, 0x41, 0x27, 0xfc, 0xe3, 0xfc, 0x99, 0xd8, 0x1d, 0x66,
	0xa8, 0xb7, 0x7c, 0xe0, 0x76, 0xb0, 0x35, 0x0b, 0x81, 0x2d, 0xd0, 0x7c, 0x49, 0xf5, 0x29, 0x0a,
	0x83, 0x6a, 0x97, 0x6c, 0x51, 0xcc, 0xf8, 0x5f, 0x3a, 0xd7, 0x2f, 0xc6, 0xee, 0x11, 0x49, 0x65,
	0x5e, 0x94, 0xac, 0x4a, 0x2d, 0x52, 0x3e, 0xa4, 0xc9, 0x2b, 0x66, 0xef, 0xb0, 0x96, 0xfb, 0x2a,
	0x47, 0x91, 0xf2, 0x7f, 0xe4, 0x4f, 0xfd, 0xf8, 0x19, 0xfa, 0x97, 0xf7, 0xb5, 0x8f, 0x3b, 0xc7,
	0x5c, 0xaa, 0x23, 0x7d, 0x82, 0x76, 0x5c, 0x77, 0x6c, 0x08, 0xde, 0xb4, 0xac, 0xe8, 0x1f, 0xb4,
	0x63, 0x5b, 0x6e, 0x7c, 0x7a, 0x9d, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x51, 0xc3,
	0xbe, 0x53, 0x02, 0x00, 0x00,
}
